import type { Track } from './types';

export const MOCK_TRACKS: Track[] = [
  {
    id: 'mock-1',
    name: 'Redbone',
    artist: 'Childish Gambino',
    artistId: 'mock-artist-1',
    album: 'Awaken, My Love!',
    image: null,
    url: 'https://open.spotify.com',
    uri: 'spotify:track:mock-1',
    durationMs: 326933,
  },
  {
    id: 'mock-2',
    name: 'Midnight City',
    artist: 'M83',
    artistId: 'mock-artist-2',
    album: "Hurry Up, We're Dreaming",
    image: null,
    url: 'https://open.spotify.com',
    uri: 'spotify:track:mock-2',
    durationMs: 244000,
  },
  {
    id: 'mock-3',
    name: 'Get Lucky',
    artist: 'Daft Punk',
    artistId: 'mock-artist-3',
    album: 'Random Access Memories',
    image: null,
    url: 'https://open.spotify.com',
    uri: 'spotify:track:mock-3',
    durationMs: 369626,
  },
  {
    id: 'mock-4',
    name: 'Instant Crush',
    artist: 'Daft Punk',
    artistId: 'mock-artist-3',
    album: 'Random Access Memories',
    image: null,
    url: 'https://open.spotify.com',
    uri: 'spotify:track:mock-4',
    durationMs: 337587,
  },
  {
    id: 'mock-5',
    name: 'Feel It Still',
    artist: 'Portugal. The Man',
    artistId: 'mock-artist-5',
    album: 'Woodstock',
    image: null,
    url: 'https://open.spotify.com',
    uri: 'spotify:track:mock-5',
    durationMs: 168718,
  },
  {
    id: 'mock-6',
    name: 'Levitating',
    artist: 'Dua Lipa',
    artistId: 'mock-artist-6',
    album: 'Future Nostalgia',
    image: null,
    url: 'https://open.spotify.com',
    uri: 'spotify:track:mock-6',
    durationMs: 203063,
  },
  {
    id: 'mock-7',
    name: 'Blinding Lights',
    artist: 'The Weeknd',
    artistId: 'mock-artist-7',
    album: 'After Hours',
    image: null,
    url: 'https://open.spotify.com',
    uri: 'spotify:track:mock-7',
    durationMs: 200040,
  },
  {
    id: 'mock-8',
    name: 'Electric Feel',
    artist: 'MGMT',
    artistId: 'mock-artist-8',
    album: 'Oracular Spectacular',
    image: null,
    url: 'https://open.spotify.com',
    uri: 'spotify:track:mock-8',
    durationMs: 229960,
  },
];
